### ISSUE TITLE
`AgentsCompletionStreamRequest` seems wrong?

### ISSUE THREAD

**Issue by RemiSaurel** [mistralai/client-ts#14]
Hi 👋

I'm trying to discover the `Agents` and use them with the API. 
The [AgentsCompletionRequest](https://github.com/mistralai/client-ts/blob/main/src/models/components/agentscompletionrequest.ts) works fine. The thing is I want to use the stream response and it seems that [AgentsCompletionStreamRequest](https://github.com/mistralai/client-ts/blob/main/src/models/components/agentscompletionstreamrequest.ts) doesn't have the required types / is not updated.

Indeed, there is missing some mandatory information (I think) such as:
- `agentId`
- `messages`

And some others that aren't necessary: 
- `model`
- `prompt`

Since I'm new on this, I might make some mistakes. Feel free to tell me!

**Comment by GaspardBT** [comment]
Thank you for testing and reporting this issue. We have identified the bug you mentioned and will release a fix soon to address it.
