### ISSUE TITLE
"trainingSteps" hyperparameter is being ignored

### ISSUE THREAD

**Issue by Kovbo** [mistralai/client-ts#34]
Running a fine-tuning job through the Mistral client, the `trainingSteps` hyperparameter is being ignored:

    const fineTuneJob = (await mistral.fineTuning.jobs.create({
      model: "mistral-small-latest",
      trainingFiles: [
        {
          fileId: trainingFile.id,
        },
      ],
      suffix,
      hyperparameters: {
        trainingSteps: 10,
        learningRate: 0.0002,
      },
      autoStart: true,
    }))
    
Dashboard:
<img width="1366" alt="1" src="https://github.com/user-attachments/assets/b6d8d775-6a76-43f6-9903-21b71d888be4">

**Comment by jean-malo** [comment]
Hello,
The training parameters is not being ignored, sorry for the confusion. You can check the full job via the api, basically if you specify training_parameters it will be converted into epochs. For this example 10 training steps corresponds to 231 epochs. 

You can also just specify epochs and you will be able to see via the API how many training steps it corresponds to. 

Thank you!
