### ISSUE TITLE
Missing support for 2411 model in GCP client?

### ISSUE THREAD

**Issue by cabljac** [mistralai/client-ts#52]
Hi, I was using the GCP SDK `and noticed I was getting 
```
API error occurred: Status 404 Content-Type application/json Body {"object":"Error","message":"The completion model `mistral-large` does not exist.","type":"invalid_request_error","code":3040}
```
Looking at the source code, I noticed it was missing here:
https://github.com/mistralai/client-ts/blob/main/packages/mistralai-gcp/src/sdk/sdk.ts#L19

Will this version of Mistral be supported? It exists on the GCP model garden

Steps to reproduce:

Using version:
```json
 "@mistralai/mistralai-gcp": "^1.3.4",
```

```typescript
import { MistralGoogleCloud } from '@mistralai/mistralai-gcp';

const client = new MistralGoogleCloud({
  region: 'us-central1', // Replace with your region
  projectId: '<PROJECT_ID>', // Replace with your project ID
});

async function chatCompletion() {
  try {
    const response = await client.chat.complete({
      model: 'mistral-large-2411', // Model name and version
      messages: [
        {
          content:
            'Who is the best French painter? Answer in one short sentence.',
          role: 'user',
        },
      ],
      maxTokens: 100,
      temperature: 0.7,
    });

    if (response.choices && response.choices.length > 0) {
      console.log('Response:', response.choices[0].message.content);
    } else {
      console.error('No choices returned in response.');
    }
  } catch (error) {
    console.error('Error during chat completion:', error);
  }
}

chatCompletion();
```

This gives:

<img width="432" alt="Screenshot 2024-12-02 at 14 27 08" src="https://github.com/user-attachments/assets/fc2c9d3f-7c45-42e6-b03e-1a0009dfab86">

But changing to 2407 suffix gives an expected response:
<img width="436" alt="Screenshot 2024-12-02 at 14 27 52" src="https://github.com/user-attachments/assets/4230b46a-1058-43d2-86dc-cec24159dcc7">

**Comment by GaspardBT** [comment]
Hi thanks for opening this issue, could you share the code snippet that you used?

**Comment by cabljac** [comment]
Sure, i'll update the issue with a repro :)

**Comment by cabljac** [comment]
I have a workaround by adding a custom hook to the HTTPClient, but it's not ideal

**Comment by GaspardBT** [comment]
Thanks for the repro, I will investigate the issue 👀 
> I have a workaround by adding a custom hook to the HTTPClient, but it's not ideal. I could make a PR to fix this, but the SDK is code gen, so didn't know what the process would be

Could you share it? Might help me debug what we are missing 🙇

**Comment by cabljac** [comment]
In fact I think I know the issue -

Basically since 2411 isn't in the map here:
https://github.com/mistralai/client-ts/blob/main/packages/mistralai-gcp/src/sdk/sdk.ts#L19

then [this function ](https://github.com/mistralai/client-ts/blob/main/packages/mistralai-gcp/src/sdk/sdk.ts#L25) is just returning `mistral-large`, which is why we get the message

```..."The completion model `mistral-large` does not exist....```

**Comment by cabljac** [comment]
amazing, thanks!

**Comment by GaspardBT** [comment]
Hum the automation closed the issue, but feel free to re-open it if the bug persist after the new release 🙇

**Comment by cabljac** [comment]
thanks for your help! Do you know roughly when the release will be out?

**Comment by GaspardBT** [comment]
> Do you know roughly when the release will be out?

The 1.3.5 release include the fix
